/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    products: Product;
    categories: Category;
    orders: Order;
    addressBook: AddressBook;
    media: Media;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  fullname: string;
  role?: ('admin' | 'user') | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  heroImage: number | Media;
  name: string;
  category?: (number | null) | Category;
  source?: string | null;
  removedStatus?: boolean | null;
  orderLimit: number;
  newArrival?: boolean | null;
  slug?: string | null;
  isFeatured?: boolean | null;
  toDisplay?: boolean | null;
  price?: number | null;
  sellingPrice?: number | null;
  stock: number;
  discount?: number | null;
  fullDescription: string;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        image?: number | Media | null;
        id?: string | null;
      }[]
    | null;
  information?:
    | {
        key?: string | null;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug?: string | null;
  image?: number | Media | null;
  products?: (number | Product)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  paymentId?: string | null;
  createdBy?: (number | null) | User;
  orderItems?:
    | {
        orderItems?: (number | null) | Product;
        price: number;
        disount: number;
        discountAmount: number;
        id?: string | null;
      }[]
    | null;
  paymentType?: string | null;
  subTotal?: number | null;
  deliveredAt?: string | null;
  shippingPrice?: number | null;
  deliveryStatus?:
    | ('DELIVERED' | 'PENDING' | 'PROCESSING' | 'CANCELLED' | 'ORDER_PLACED' | 'DISPATCHED' | 'ON_THE_WAY')
    | null;
  paymentStatus?: ('PENDING' | 'PAID') | null;
  grandTotal?: number | null;
  billingAddress?: (number | null) | AddressBook;
  shippingAddress?: (number | null) | AddressBook;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addressBook".
 */
export interface AddressBook {
  id: number;
  user?: (number | null) | User;
  defaultDeliveryAddress?: boolean | null;
  defaultBillingAddress?: boolean | null;
  name?: string | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  apartmentNumber?: string | null;
  city?: string | null;
  postalCode?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'orders';
        value: number | Order;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}